using System.Collections;
using System.Collections.Generic;
using UnityEngine;
using UnityEngine.SceneManagement;
using UnityEngine.UI;

public class pawsmenu : MonoBehaviour
{
    // Start is called before the first frame update
    void Start()
    {
        GetComponent<Canvas>().enabled = false;
    }

    // Update is called once per frame
    void Update()
    {
        if (Input.GetKeyDown(KeyCode.Escape))
        {
            if (Time.timeScale == 1)
            {
                Time.timeScale = 0;
                GetComponent<Canvas>().enabled = true;
            }
            else
            {
                Time.timeScale = 1;
                GetComponent<Canvas>().enabled = false;
            }
        }
    }

    public void resume()
    {
        Time.timeScale = 1;
        GetComponent<Canvas>().enabled = false;
    }

    public void loadmainmenu()
    {
        Time.timeScale = 1;
        SceneManager.LoadScene("main menu");
    }

    public void quitgame()
    {
        Application.Quit();
    }

    public void settings()
    {

    }
}
